import type { StrategicSpec } from "./strategic-market-data";

export const marketRefreshDate = "2026-10-01";
export const refreshedSources: Record<string,{name:string,url:string}> = {
  "byd-co":{name:"BYD Colombia｜Motorysa 官方乘用车型目录",url:"https://bydauto.com.co/modelos/"},
  "chery-co":{name:"Chery Colombia｜本地车型与起售价",url:"https://www.chery.com.co/"},
  "chery-co-e5":{name:"Chery Colombia｜E5 预订与配置",url:"https://www.chery.com.co/chery-e5/"},
  "chery-co-icar":{name:"Chery Colombia｜iCAR 03 配置",url:"https://www.chery.com.co/icar-03/"},
  "chery-co-orders":{name:"Chery Colombia｜官方预订目录",url:"https://www.chery.com.co/pedidos/"},
  "jetour-co":{name:"Jetour Colombia｜Autocom 官方车型与起售价",url:"https://jetour.com.co/nuestros-vehiculos/"},
  "geely-co":{name:"Geely Colombia｜本地车型目录",url:"https://geely.com.co/"},
  "zeekr-co":{name:"Zeekr Colombia｜本地车型与订购",url:"https://store.zeekrco.com/"},
  "gwm-co":{name:"GWM Colombia｜本地车型目录",url:"https://www.gwm.com.co/"},
  "gwm-co-h6":{name:"GWM Colombia｜Haval H6 本地动力与售价",url:"https://www.gwm.com.co/vehiculo/haval/nueva-h6-hev/"},
  "gwm-co-ora5":{name:"GWM Colombia｜ORA 5 SUV 配置、电池与售价",url:"https://www.gwm.com.co/vehiculo/ora/ora-5-suv/"},
  "gwm-co-poer":{name:"GWM Colombia｜Poer Commercial 配置与售价",url:"https://www.gwm.com.co/vehiculo/poer/poer-mecanica/"},
  "voyah-co":{name:"VOYAH Colombia｜本地官方车型目录",url:"https://www.voyahcolombia.com/"},
  "changan-co":{name:"Changan Colombia｜本地官方车型目录",url:"https://changan.com.co/"},
  "nevo-co":{name:"Changan Colombia｜NEVO Q05 官方预订",url:"https://changan.com.co/nevo-q05/"},
  "deepal-co":{name:"Deepal Colombia｜本地动力版本目录",url:"https://www.deepalcolombia.com.co/"},
  "xpeng-co":{name:"XPENG Colombia｜本地车型与起售价",url:"https://www.xpeng.com/co/"},
  "xpeng-co-g6":{name:"XPENG Colombia｜G6 配置与售价",url:"https://www.xpeng.com/co/vehiculo/xpeng-g6"},
  "gac-co-ut":{name:"GAC Colombia｜AION UT 三种电池及续航",url:"https://gacmotorcolombia.com/aion-ut?version=light"},
  "gac-co":{name:"GAC Colombia｜本地官方车型目录",url:"https://gacmotorcolombia.com/"},
  "gac-co-s7":{name:"GAC Colombia｜S7 REEV AWD 预售、配置与标价（9月促销已到期）",url:"https://gacmotorcolombia.com/s7"},
  "chery-co-icar03t":{name:"Chery Colombia｜iCAR 03T 增程预售（预计 11 月交付）",url:"https://www.chery.com.co/icar-03t/"},
  "gwm-au-ora5":{name:"GWM Australia｜ORA 5 售价与配置",url:"https://www.gwmanz.com/au/models/suv/ora-5-suv/"},
  "gwm-nz-ora5":{name:"GWM New Zealand｜ORA 5 售价与配置",url:"https://www.gwmanz.com/nz/models/suv/ora-5-suv/"},
  "gwm-th-g9":{name:"GWM Thailand｜WEY G9 订购与售价",url:"https://www.gwm.co.th/en/models/wey-g9"},
  "gwm-my-g9":{name:"GWM Malaysia｜WEY G9 本地售价与配置",url:"https://www.gwm.com.my/en/models/wey-g9"},
  "gwm-th-ora5":{name:"GWM Thailand｜ORA 5 EV 订购与售价",url:"https://www.gwm.co.th/en/models/ora-5-ev"},
  "gwm-th-ora5-hev":{name:"GWM Thailand｜ORA 5 HEV 订购与 MSRP",url:"https://www.gwm.co.th/en/models/ora-5-hev"},
  "gwm-th-sahar":{name:"GWM Thailand｜POER SAHAR Diesel 官方配置与 MSRP",url:"https://www.gwm.co.th/en/models/sahar-diesel"},
  "gwm-th-tank300":{name:"GWM Thailand｜TANK 300 HEV 官方目录与 MSRP（保留 HEV）",url:"https://www.gwm.co.th/en/models/tank-300"},
  "gwm-th-tank500":{name:"GWM Thailand｜TANK 500 HEV 官方目录与 MSRP（保留 HEV）",url:"https://www.gwm.co.th/en/models/tank-500"},
  "jetour-uy-g700":{name:"Jetour Uruguay｜G700 插混车型与售价",url:"https://jetour.com.uy/g700/"},
  "chery-ec-eq7":{name:"Chery Ecuador｜EQ7 车型与配置表",url:"https://www.chery.com.ec/vehiculo/eq7"},
};

// Country × brand × model is the replacement unit. Untouched records retain
// their original verification dates. Prices are local currency, not USD.
const row=(group:string,brand:string,model:string,source:string,trims:string,price?:string)=>
  `${group}集团|${brand}|${model}|${price||trims.split(",")[0].split(":").at(-1)}|${trims}|${source}`;
const co=(group:string,brand:string,model:string,source:string,trims:string)=>row(group,brand,model,source,trims);
export const marketRefreshRaw: Record<string,string[]> = {
  "哥伦比亚":[
    co("BYD","BYD","Dolphin Mini","byd-co","BEV GL FWD:询价,BEV GS FWD:询价"),
    co("BYD","BYD","Dolphin","byd-co","BEV FWD:询价"),
    co("BYD","BYD","Yuan Up","byd-co","BEV FWD:询价"),
    co("BYD","BYD","Yuan Plus","byd-co","BEV LUX FWD:询价"),
    co("BYD","BYD","Song Plus","byd-co","BEV FWD:询价,PHEV DM-i 1.5T FWD:询价"),
    co("BYD","BYD","Tang","byd-co","BEV GS AWD:询价"),
    co("BYD","BYD","Sealion 7","byd-co","BEV 当地驱动未公布:询价"),
    co("BYD","BYD","Shark","byd-co","PHEV DM-O AWD:询价"),
    co("Chery","Chery","Omoda E5","chery-co-e5","BEV Comfort FWD 预售:COP 79.990.000,BEV Luxury Full FWD 预售:询价"),
    co("Chery","Chery","iCAR 03","chery-co-icar","BEV AllRoad RWD:COP 119.990.000,BEV iWD AWD:询价"),
    co("Chery","Chery","iCAR 03T","chery-co-icar03t","REEV iWD AWD 预售 11月交付:COP 129.990.000"),
    co("Chery","Chery","Tiggo 4 CSH","chery-co","HEV FWD:COP 104.990.000"),
    co("Chery","Chery","Tiggo 7","chery-co","MHEV PRO FWD:COP 109.990.000,PHEV CSH FWD:COP 129.990.000"),
    co("Chery","Chery","Tiggo 8 Pro","chery-co","PHEV CSH FWD:COP 145.990.000"),
    co("Chery","Chery","Tiggo 9","chery-co","PHEV CSH AWD:COP 210.990.000"),
    co("Chery","Jetour","Jetour X50","jetour-co","ICE FWD:COP 69.990.000"),
    co("Chery","Jetour","Jetour X70","jetour-co","ICE Sport FWD:COP 96.990.000,ICE Limited FWD:COP 106.990.000,ICE Plus FWD:COP 120.990.000"),
    co("Chery","Jetour","Jetour Dashing","jetour-co","ICE FWD:COP 103.990.000"),
    co("Chery","Jetour","Jetour T1","jetour-co","PHEV iDM 当地驱动未公布:COP 162.990.000"),
    co("Chery","Jetour","Jetour T2","jetour-co","PHEV iDM 当地驱动未公布:COP 185.990.000"),
    co("Geely","Geely","EX2","geely-co","BEV Pro RWD:COP 69.990.000,BEV Max RWD:询价"),
    co("Geely","Geely","EX5","geely-co","BEV SE FWD:COP 89.990.000"),
    co("Geely","Geely","EX5 EM-i","geely-co","PHEV Starray Pro FWD:COP 125.990.000,PHEV Starray Max FWD:询价"),
    co("Geely","Zeekr","Zeekr X","zeekr-co","BEV 当地驱动未公布:询价"),
    co("Geely","Zeekr","Zeekr 001","zeekr-co","BEV 当地驱动未公布:询价"),
    co("Geely","Zeekr","Zeekr 7X","zeekr-co","BEV 当地驱动未公布:询价,BEV Flagship AWD:询价"),
    co("GWM","GWM","Ora 5","gwm-co-ora5","BEV MID FWD:COP 79.900.000,BEV TOP FWD:COP 94.900.000"),
    co("GWM","GWM","Haval Jolion","gwm-co","HEV TOP FWD:COP 119.900.000"),
    co("GWM","GWM","Haval H6","gwm-co","HEV FWD:COP 139.900.000,PHEV AWD:COP 161.900.000"),
    co("GWM","GWM","Haval H7","gwm-co","HEV 当地驱动未公布:COP 149.900.000"),
    co("GWM","GWM","Tank 300","gwm-co","HEV AWD:COP 199.900.000"),
    co("GWM","GWM","Tank 500","gwm-co","HEV AWD:COP 259.900.000"),
    co("GWM","GWM","Poer","gwm-co","Diesel Commercial 当地驱动未公布:COP 119.900.000,Diesel Passenger 2.4 AWD:COP 199.900.000"),
    co("东风","VOYAH","VOYAH Courage","voyah-co","BEV RWD:询价"),
    co("东风","VOYAH","VOYAH Free","voyah-co","REEV 318 AWD:询价"),
    co("Changan","Changan","CS15","changan-co","ICE FWD:询价"),
    co("Changan","Changan","CS35 Plus","changan-co","ICE Turbo FWD:询价"),
    co("Changan","Changan","CS55 Plus","changan-co","ICE Turbo FWD:询价"),
    co("Changan","Changan","Hunter","changan-co","REEV PRO AWD:询价,REEV Luxury AWD:询价"),
    co("Changan","NEVO","NEVO Q05","nevo-co","BEV E-MAX FWD 预售:COP 79.990.000,BEV E-MAX Ultra FWD 预售:COP 89.990.000"),
    co("Changan","Deepal","Deepal S05","deepal-co","REEV MAX RWD:询价,BEV E-MAX RWD:询价"),
    co("Changan","Deepal","Deepal S07","deepal-co","REEV MAX RWD:询价,BEV E-MAX RWD:询价"),
    co("Changan","Deepal","Deepal G318","deepal-co","REEV MAX Adventure AWD:询价"),
    co("XPENG","XPENG","XPENG G6","xpeng-co-g6","BEV Standard Range Air RWD:COP 149.990.000,BEV Long Range Pro RWD:询价"),
    co("XPENG","XPENG","XPENG G9","xpeng-co","BEV 当地驱动未公布:COP 254.990.000"),
    co("GAC","GAC","GS3 EMZOOM","gac-co","ICE Comfort FWD:COP 109.990.000,ICE R-Style FWD:询价"),
    co("GAC","GAC","EMKOO","gac-co","HEV FWD:COP 159.990.000"),
    co("GAC","GAC","S7","gac-co-s7","REEV AWD 预售:COP 164.990.000"),
    co("GAC","AION","AION UT","gac-co-ut","BEV Light FWD:COP 63.990.000,BEV Elite FWD:询价,BEV Premium FWD:询价"),
    co("GAC","AION","AION V","gac-co","BEV 500 FWD:COP 125.990.000,BEV 600 FWD:询价"),
    co("GAC","AION","AION Y Plus","gac-co","BEV FWD:COP 107.990.000"),
    co("GAC","AION","AION ES","gac-co","BEV FWD:COP 94.990.000"),
    co("GAC","HYPTEC","HYPTEC HT","gac-co","BEV RWD:COP 184.990.000,BEV Gullwing RWD:询价"),
  ],
  "阿根廷":[
    row("GWM","GWM","Ora 5","gwm-ar","HEV FWD:询价"),
    row("GWM","GWM","Haval Jolion","gwm-ar","HEV PRO FWD:询价"),
    row("GWM","GWM","Haval H7","gwm-ar","ICE 当地驱动未公布:询价,HEV 当地驱动未公布:询价"),
    row("GWM","GWM","Haval H6","gwm-ar","HEV PRO FWD:询价,ICE FWD:询价,ICE GT AWD:询价"),
  ],
  "智利":[
    row("GWM","GWM","Ora 5","gwm-cl","BEV FWD:CLP 22.990.000"),
    row("GWM","GWM","Ora 03","gwm-cl","BEV FWD:CLP 17.990.000"),
    row("GWM","GWM","Haval H7","gwm-cl","ICE 当地驱动未公布:CLP 21.690.000,HEV 当地驱动未公布:询价,HEV MAX 当地驱动未公布:CLP 27.490.000,PHEV MAX 当地驱动未公布:询价"),
    row("GWM","GWM","Poer P500","gwm-cl","PHEV AWD:CLP 38.990.000 + IVA"),
    row("GWM","GWM","Wingle 7","gwm-cl","Gasolina 当地驱动未公布:CLP 12.390.000 + IVA,Diesel 当地驱动未公布:询价"),
    row("BYD","BYD","Sealion 7","byd-cl","BEV 当地驱动未公布:询价"),
    row("BYD","BYD","Atto 8","byd-cl","PHEV AWD:询价"),
  ],
  "乌拉圭":[
    row("GWM","GWM","Ora 5","gwm-uy","BEV FWD:US$ 24.990"),
    row("GWM","GWM","Haval H7","gwm-uy","PHEV 当地驱动未公布:US$ 38.990"),
    row("GWM","GWM","Tank 300","gwm-uy","HEV AWD:US$ 59.990"),
    row("Chery","Chery","M7","chery-uy","ICE FWD:US$ 23.990"),
    row("Chery","Chery","Himla","chery-uy","Diesel AWD 企业价:US$ 33.990"),
    row("Chery","Jetour","Jetour G700","jetour-uy-g700","PHEV AWD:US$ 79.990"),
    row("Chery","Jetour","Jetour X50","jetour-uy","ICE MT FWD:询价,ICE AT FWD:询价"),
    row("Chery","Jetour","Jetour Dashing","jetour-uy","ICE FWD:询价"),
    row("Chery","Jetour","Jetour T1","jetour-uy","ICE 当地驱动未公布:询价,PHEV 当地驱动未公布:询价"),
    row("Chery","Jetour","Jetour T2","jetour-uy","ICE AWD:询价,PHEV 当地驱动未公布:询价"),
    row("BYD","BYD","Atto 8","byd-uy","PHEV AWD:询价"),
  ],
  "厄瓜多尔":[
    row("Chery","Chery","EQ7","chery-ec-eq7","BEV RWD:US$ 37.990"),
    row("Chery","Chery","Arrizo 5 Pro","chery-ec","ICE Pro Max FWD:US$ 16.990"),
    row("Chery","Chery","Himla","chery-ec","Diesel 当地驱动未公布:US$ 28.990"),
    row("Chery","Chery","Tiggo 9","chery-ec","PHEV CSH AWD:US$ 46.990"),
    row("Chery","Chery","Tiggo 2 Pro","chery-ec","ICE Max FWD:US$ 18.490"),
    row("Chery","Chery","Tiggo 4","chery-ec","ICE Pro FWD:US$ 19.990"),
    row("Chery","Chery","Tiggo 7","chery-ec","ICE Pro Max FWD:US$ 24.990,PHEV CSH FWD:US$ 30.990"),
    row("Chery","Chery","Tiggo 8 Pro","chery-ec","PHEV CSH FWD:US$ 38.990"),
    row("Geely","Geely","EX2","geely-ec","BEV RWD:US$ 18.990"),
    row("Geely","Geely","EX5","geely-ec","BEV FWD:US$ 25.990"),
    row("Geely","Geely","EX5 EM-i","geely-ec","PHEV Starray FWD:US$ 28.990"),
    row("BYD","BYD","Atto 8","byd-ec","PHEV AWD:询价"),
  ],
  "澳大利亚":[
    row("GWM","GWM","Ora 5","gwm-au-ora5","BEV Lux FWD:AUD 33.990,BEV Ultra FWD:AUD 36.990"),
    row("Chery","Chery","Tiggo 9","chery-au","PHEV Super Hybrid AWD:询价"),
    row("Chery","Chery","Omoda 5","chery-au","ICE C5 FWD:AUD 28.990,HEV C5 FWD:询价"),
    row("Chery","Chery","Omoda E5","chery-au","BEV E5 FWD:询价"),
    row("Chery","Jaecoo","Jaecoo 5","oj-au","BEV FWD:询价,HEV SHS-H Summit FWD:AUD 34.990"),
    row("Chery","Jaecoo","Jaecoo 8","oj-au","PHEV SHS-P Summit AWD 7 Seats:询价"),
  ],
  "新西兰":[
    row("GWM","GWM","Ora 5","gwm-nz-ora5","BEV Lux FWD:NZ$ 36.990 + ORC,BEV Ultra FWD:NZ$ 39.990 + ORC"),
    row("Chery","Chery","Tiggo 9","chery-nz","PHEV Ultimate AWD:NZ$ 66.990 + ORC"),
    row("Chery","Jaecoo","Jaecoo 5","oj-nz","BEV FWD:询价,HEV Hybrid FWD:询价"),
    row("Chery","Jaecoo","Jaecoo 8","oj-nz","PHEV SHS AWD:询价"),
  ],
  "泰国":[
    row("GWM","GWM","Ora 5","gwm-th-ora5-hev","BEV FWD MSRP:THB 669.000,HEV FWD MSRP:THB 729.000"),
    row("GWM","GWM","Poer","gwm-th-sahar","Diesel SAHAR SINGLE CAB 4x2 MSRP:THB 849.000,Diesel SAHAR PRO 4x2:询价,Diesel SAHAR ULTRA 4x2:询价,Diesel SAHAR ULTRA 4x4:询价"),
    row("GWM","GWM","WEY G9","gwm-th-g9","PHEV Hi4 Ultra AWD:THB 2.349.000"),
    row("GWM","GWM","Tank 300","gwm-th-tank300","Diesel AWD:询价,HEV AWD MSRP:THB 1.799.000"),
    row("GWM","GWM","Tank 500","gwm-th-tank500","Diesel AWD:询价,HEV AWD MSRP:THB 2.049.000"),
  ],
  "马来西亚":[row("GWM","GWM","WEY G9","gwm-my-g9","PHEV Hi4 Ultra AWD:MYR 269.800")],
  "英国":[row("GAC","AION","AION UT","gac-uk","BEV FWD:£ 28.950"),row("GAC","AION","AION V","gac-uk","BEV FWD:£ 36.450")],
  "以色列":[row("GAC","AION","AION UT","gac-il","BEV FWD:询价"),row("Geely","Geely","EX5 EM-i","geely-il","PHEV Starray FWD:询价")],
  ...Object.fromEntries([["挪威","nio-no"],["荷兰","nio-nl"],["瑞典","nio-se"],["德国","nio-de"]].map(([country,source])=>[country,[row("NIO","NIO","NIO ET7",source,"BEV AWD 当地电池版本询价:询价"),row("NIO","NIO","NIO EL7",source,"BEV AWD 当地电池版本询价:询价")]])),
};
const spec=(dims:string,wheelbase:string,energy:string,range="当地官网未公布"):StrategicSpec=>({dims,wheelbase,energy,use:"当地官网未公布",range,safety:"未查到适用版本有效五星成绩",rating:"unknown"});
export const refreshSpecs: Record<string,StrategicSpec> = {
  "Ora 5":spec("4,471 × 1,833 × 1,641 mm（澳新规格）","2,720 mm（澳新规格）","纯电 BEV / 油电混动 HEV"),
  "iCAR 03":spec("4,342 × 1,930 × 1,741 mm","2,715 mm","纯电 BEV","410–421 km NEDC（依配置）"),
  "iCAR 03T":spec("4,503 × 1,950 × 1,815 mm","2,783 mm","增程 REEV","160 km 纯电 NEDC / 801 km 综合 WLTC"),
  "NEVO Q05":spec("4,435 × 1,855 × 1,600 mm","2,735 mm","纯电 BEV","455 km NEDC"),
  "Jetour G700":spec("5,198 × 2,050 × 1,956 mm（全球规格）","2,870 mm（全球规格）","插混 PHEV","超过 1,400 km 综合（当地官网未标明循环）"),
  "EQ7":spec("4,675 × 1,910 × 1,660 mm","2,830 mm","纯电 BEV","512 km（当地官网未标明循环）"),
  "WEY G9":spec("5,050 × 1,985 × 1,900 mm","3,085 mm","插混 PHEV","170 km 纯电 NEDC / 超过 1,000 km 综合 NEDC"),
  "NIO ET7":spec("5,101 × 1,987 × 1,509 mm","3,060 mm","纯电 BEV"),
  "NIO EL7":spec("4,912 × 1,987 × 1,720 mm","2,960 mm","纯电 BEV"),
};
export const refreshImages: Record<string,string> = {
  "Ora 5":"/cars/ora-5.png","iCAR 03":"/cars/icar-03.jpg","iCAR 03T":"/cars/icar-03t.png",
  "NEVO Q05":"/cars/nevo-q05.webp","Jetour G700":"/cars/jetour-g700.jpg","EQ7":"/cars/eq7.png",
  "WEY G9":"/cars/wey-g9.png","NIO ET7":"/cars/nio-et7.jpg","NIO EL7":"/cars/nio-el7.jpeg",
};
export const refreshDrive: Record<string,string> = {"Ora 5":"前驱","iCAR 03":"后驱 / 四驱","iCAR 03T":"四驱","NEVO Q05":"前驱","Jetour G700":"四驱","EQ7":"后驱","WEY G9":"四驱","NIO ET7":"四驱","NIO EL7":"四驱"};
// Do not inherit another country's battery/range figures for Colombia.
export const refreshMarketSpecs: Record<string,Partial<StrategicSpec>> = {
  ...Object.fromEntries(marketRefreshRaw["哥伦比亚"].map(line=>["哥伦比亚|"+line.split("|")[2],{use:"当地官网未公布",range:"当地官网未按配置公布"}])),
  "哥伦比亚|Omoda E5":{dims:"4,545 × 1,830 × 1,588 mm",wheelbase:"2,630 mm",range:"422 km NEDC"},
  "哥伦比亚|iCAR 03T":{range:"160 km 纯电 NEDC / 801 km 综合 WLTC"},
  "哥伦比亚|NEVO Q05":{range:"455 km NEDC"},
  "哥伦比亚|S7":{dims:"4,900 × 1,950 × 1,780 mm",wheelbase:"2,880 mm",energy:"增程 REEV",range:"153 km 纯电 / 860 km 综合 NEDC"},
  "哥伦比亚|Ora 5":{dims:"4,471 × 1,833 × 1,641 mm",wheelbase:"2,720 mm",range:"520 km NEDC"},
  "哥伦比亚|VOYAH Free":{energy:"增程 REEV",range:"1,357 km 综合 CLTC"},
  "哥伦比亚|VOYAH Courage":{range:"625 km CLTC"},
  "哥伦比亚|iCAR 03":{range:"410–421 km NEDC（依配置）"},
  "澳大利亚|Ora 5":{range:"435 km WLTC",use:"15.5 kWh/100km WLTC"},
  "新西兰|Ora 5":{range:"435 km WLTC",use:"15.5 kWh/100km WLTC"},
};
export const refreshBatteryDetails: Record<string,{battery:string;range:string}> = {
  "哥伦比亚|NEVO Q05|纯电":{battery:"51.9 kWh",range:"455 km NEDC"},
  "哥伦比亚|S7|增程":{battery:"36.3 kWh",range:"153 km 纯电 / 860 km 综合 NEDC"},
  "哥伦比亚|Dolphin Mini|BEV GL FWD":{battery:"当地官网未按配置公布",range:"300 km NEDC"},
  "哥伦比亚|Dolphin Mini|BEV GS FWD":{battery:"当地官网未按配置公布",range:"380 km NEDC"},
  "哥伦比亚|Song Plus|纯电":{battery:"71.8 kWh",range:"405 km WLTP"},
  "哥伦比亚|Omoda E5|纯电":{battery:"50.6 kWh",range:"422 km NEDC"},
  "哥伦比亚|iCAR 03T|增程":{battery:"34.31 kWh",range:"160 km 纯电 NEDC / 801 km 综合 WLTC"},
  "哥伦比亚|iCAR 03|BEV AllRoad RWD":{battery:"65.69 kWh",range:"410 km NEDC"},
  "哥伦比亚|iCAR 03|BEV iWD AWD":{battery:"69.77 kWh",range:"421 km NEDC"},
  "哥伦比亚|VOYAH Free|增程":{battery:"43 kWh",range:"1,357 km 综合 CLTC"},
  "哥伦比亚|VOYAH Courage|纯电":{battery:"80 kWh",range:"625 km CLTC"},
  "哥伦比亚|Ora 5|纯电":{battery:"58.33 kWh",range:"520 km NEDC"},
  "哥伦比亚|AION UT|BEV Light FWD":{battery:"32.24 kWh",range:"300 km NEDC"},
  "哥伦比亚|AION UT|BEV Elite FWD":{battery:"44.12 kWh",range:"400 km NEDC"},
  "哥伦比亚|AION UT|BEV Premium FWD":{battery:"60 kWh",range:"500 km NEDC"},
  "哥伦比亚|XPENG G6|BEV Standard Range Air RWD":{battery:"当地官网页面存在冲突，待配置表核验",range:"455 km WLTP"},
  "哥伦比亚|XPENG G6|BEV Long Range Pro RWD":{battery:"当地官网未按配置公布",range:"520 km WLTP"},
  "澳大利亚|Ora 5|纯电":{battery:"58.33 kWh",range:"435 km WLTC"},
  "新西兰|Ora 5|纯电":{battery:"58.33 kWh",range:"435 km WLTC"},
  "泰国|Ora 5|纯电":{battery:"58.3 kWh",range:"520 km NEDC"},
  "厄瓜多尔|EQ7|纯电":{battery:"65.5 kWh",range:"512 km（当地官网未标明循环）"},
  "泰国|WEY G9|插混":{battery:"44.2 kWh",range:"170 km 纯电 NEDC"},
  "马来西亚|WEY G9|插混":{battery:"44.2 kWh",range:"170 km 纯电 / 超过 1,000 km 综合 NEDC"},
};

export const refreshedRecordKeys=new Set(Object.entries(marketRefreshRaw).flatMap(([country,rows])=>rows.map(line=>`${country}|${line.split("|").slice(0,3).join("|")}`)));
export function applyMarketRefresh(base:Record<string,string[]>):Record<string,string[]> {
  const merged={...base};
  for(const [country,updates] of Object.entries(marketRefreshRaw)){
    const keys=new Set(updates.map(line=>line.split("|").slice(0,3).join("|")));
    merged[country]=[...(base[country]||[]).filter(line=>!keys.has(line.split("|").slice(0,3).join("|"))),...updates];
  }
  return merged;
}
